### ISSUE TITLE
Study page

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#3]
This ticket is for the individual page each study will have.

![study-adding-document](https://cloud.githubusercontent.com/assets/739624/11899324/fa69cfb8-a595-11e5-91a9-9a78c094c176.png)

### Anyone
- [x] Can see the stage the study is at
- [x] Can see the basic details of the study (*exact details TBC*)
- [x] Can see a timeline of the activity on the study
- [x] Can access publications attached to the study
- [ ] Can follow the study (See #20)

### Logged in users
- [x] Can download the documents attached to a study (#66)

### Administrators
- [x] Can change the principal investigator of the study
- [x] Can assign the study to a research manager
- [x] Can change the basic details of the study
- [x] Can change the stage the study is at
- [x] Can progress the study to delivery or completion
- [x] Can add a note (See #19)
- [x] Can upload a new document
- [x] Can add evidence of impact the study has had (publications, disseminations and other impacts)
- [x] Can add enabler/barriers to the study

### Contributors
- [x] Can add a note (See #19)
- [x] Can upload a new document
- [x] Can add evidence of impact the study has had (publications, disseminations and other impacts)
- [x] Can add enabler/barriers to the study
- [ ] Can add details of collaborators (#100) 
- [x] Can progress the study to delivery or completion

**Comment by stevenday** [comment]
@zarino - can you clarify what you were intending with the recent action card in the top right of the design? (The bit that says: "Protocol revision requested, since 11th November, read ERB feedback document")

I'm not sure where this type of event/action is coming from, or what other things are likely to be there, because they're not statuses/events that I have in any of the fields on a study. 

Is this from when we talked about breaking down the ERB process more granularly? (And hence should be removed because we're not doing that any more), or something else that I've missed?

**Comment by zarino** [comment]
I was expecting it to just be the most recent thing from the timeline at the bottom. So it could be anything that can appear in the timeline.

**Comment by stevenday** [comment]
Ah ok - that makes more sense - thanks!

**Comment by zarino** [comment]
See also https://github.com/mysociety/remit/issues/72 for deciding how to display publications, disseminations, and other impacts, in the timeline and sidebar of this page.

**Comment by zarino** [comment]
@stevenday – Regarding the hints that need to be displayed under dissemination categories…

![screen shot 2016-01-29 at 15 54 46](https://cloud.githubusercontent.com/assets/739624/12680244/a857a494-c6a0-11e5-81fe-1822285df68d.png)

It looks like [this javascript plugin](https://github.com/silviomoreto/bootstrap-select) will construct the sort of dropdowns we need, and can handle custom subtext beneath/beside each menu item:

![screen shot 2016-01-29 at 15 50 12](https://cloud.githubusercontent.com/assets/739624/12680268/c9001abe-c6a0-11e5-8c58-d1a2356ac9e0.png)

Appears to be well supported, and under fairly active development. Is there some Rails-approved way of getting this "installed" into the app?

**Comment by stevenday** [comment]
Interesting!

It looks like someone has made a very rails-y way of including it as a gem,
however, it's a bit out of date:
https://github.com/Slashek/bootstrap-select-rails

There are some more up to date forks of that, but to be honest, unless it
needs loads of stuff, I would just vendor it (copy the js into
vendor/assets/javascripts and the sass into vendor/assets/stylesheets) and
then you can reference them from app/assets/javascripts/application.js and
app/assets/stylesheets/application.scss like any other file.

**Comment by stevenday** [comment]
I've updated the list of users stories here to capture the changes from #100, #18 and #66.

**Comment by stevenday** [comment]
This page should now be totally finished (apart from the omission of following studies). I'm moving it over to review for @kimmwest to look over in full.

In this sprint we've added:
- A new separate page for adding impacts
- A way to invite users to contribute to the study
- Items like the study PI, topic, location now function as links to searches for other similar studies
- Publications can be added by DOI number as well as manually
- When a study is in protocol & erb, the PI/RM can click a button to progress it to delivery
- When a study is in delivery, the PI/RM can click a button to progress it to completion
- Only logged in users can download the documents attached to a study

**Comment by kimmwest** [comment]
Hi @stevenday - on the 'add impact' section the 'other' and 'patients' categories do not automatically open a free text box.  
Also, when I tried to add impact information across multiple categories at once I got a 'description can't be black' error message 

I think for the 'disemmination categories it makes sense for those to be tick boxes too because (like impact) they could have disemminated in more than one of those forums

**Comment by kimmwest** [comment]
Everything else looks great!
